[package]
name = "flac-benchmark"
version = "0.1.0"
authors = ["Simon Persson <simon@flaskpost.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metaflac = "0.2.2"
walkdir = "2.3.1"
